apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - green/ # Point to the green environment (new version)
  # - blue/                            # Comment this line if switching to green
  - ../../../base/hpa.yaml # Include base HPA file (no patch required)
