apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: frontend-service
spec:
  type: LoadBalancer
  selector:
    app: frontend-pod
    ports:
      protocol: TCP
      port: 80
      targetPort: 80
