apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backend-stable
spec:
  destination:
    namespace: backend
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/my-org/gitops-repo.git
    targetRevision: HEAD
    path: overlays/blue
    kustomize:
      namePrefix: blue-
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
