apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend-prod
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: backend
  source:
    repoURL: "https://github.com/Vikas-Prince/"
    targetRevision: HEAD
    path: overlays/stage
    kustomize:
      - namePrefix: canary-
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
