apiVersion: v1
kind: Service
metadata:
  name: frontend-blue
  namespace: frontend
spec:
  type: LoadBalancer
  selector:
    app: frontend-blue
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-green
  namespace: frontend
spec:
  type: LoadBalancer
  selector:
    app: frontend-green
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
