apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/service.yaml
  - ../../base/hpa.yaml
  - ../../base/secret.yaml
  - canary/  # Point to the canary overlay which applies patches
